### PR TITLE
Make `test.todo(title, fn)` produce a failure

### LINKED ISSUE #697: `test.todo(title, fn)` should produce a failure
## Overview: 

My understanding of the `skip` vs `todo` vs `failing` API was:

1. `test.skip([title], fn)` - A test function is provided, but it is skipped(i.e. `fn` is never called). Common use: removing a failing test while you are in the middle of refactoring. People probably shouldn't be checking `test.skip` tests into their master branch (especially once `test.failing` is implemented). Title is optional, just like the normal `test` method.

2. `test.todo(title)` - No test function is allowed, but a title is required. Common use: documenting future tests (and maybe features) that need to be written.

3. `test.failing([title], fn)` - Proposed in #673- Optional title, test function is required and **will** be run (but is expected to fail). Common use: allow users to create PR's that reproduce the problem. Reporting bugs in a way that does not break the build.

--- 

## Issue:

Right now the API for `2` is more like: `test.todo(title, [fn])` - `title` is required, but `fn` is optional (and ignored).

### PR DESCRIPTION
**Pull request by sotojuan**
Fixes #697.

Let me know if a better error message helps!

### CODE REVIEW

**Comment by jamestalmage** [comment]
I think the message should include instructions to "use `test.skip` instead".

When #673 lands we can amend it to say "use `test.skip` or `test.fail` instead".

Otherwise :+1:

File: lib/runner.js [hunk 1]
```diff
@@ -57,6 +57,10 @@ optionChain(chainableMethods, function (opts, title, fn) {
 		title = null;
 	}
 
+	if (opts.todo && typeof fn === 'function') {
+		throw new TypeError('`todo` tests are not allowed to have a function. Use `test.skip()` for tests with a function.');
+	}
+
```
Comment (novemberborn) [inline lib/runner.js]: Should combine this with the if-block below which also applies to `opts.todo`.

**Comment by novemberborn** [comment]
I wonder whether we should change "function" here (and in the other messages) to "implementation". It's currently [named `callback` in the docs](https://github.com/sindresorhus/ava#callbackt). I struggled quite  a bit with the wording there.

File: lib/runner.js (hunk 1 above)
Comment (sotojuan) [inline lib/runner.js]: That's what I was doing before but it wasn't working because of the `fn = noop` line (which seems to be used to "override" any given function), and if I removed that other stuff broke.

Comment (novemberborn) [inline lib/runner.js]: Try setting `fn = noop` after testing `fn`.

Comment (sotojuan) [inline lib/runner.js]: Got it working, thanks!

**Comment by sotojuan** [comment]
You guys decide! Let me know—either seems clear to me.

**Comment by jamestalmage** [comment]
Use implementation.

**Comment by sotojuan** [comment]
All right, changed to "implementation". If it looks good I can do a PR for the other messages.

**Comment by novemberborn** [comment]
Thanks @sotojuan!

> If it looks good I can do a PR for the other messages.

That'd be great. Could you update the readme as well?
