### PR TITLE
Test watcher from the CLI

### LINKED ISSUE #537: test/cli needs to test --watch
The test for `lib/watcher.js` are fully stubbed so changes to the API may break the watcher without failing any tests. Need to add an integration test to `test/cli.js`.

The test should probably trigger a file change. We can look to nodemon for [inspiration](https://github.com/remy/nodemon/blob/master/test/monitor/run.test.js#L30:L44).

Since `chokidar` is an optional dependency the test may fail on platforms where it cannot be installed. This should cause the test to be skipped, not fail.

### PR DESCRIPTION
**Pull request by novemberborn**
The watcher tests are fully stubbed. This test verifies it actually works from the CLI.

Fixes #537.

### CODE REVIEW

File: test/fixture/watcher/test.js [hunk 1]
```diff
@@ -0,0 +1,5 @@
+import test from '../../../';
+
+test('works', t => {
+	t.ok(true);
```
Comment (sindresorhus) [inline test/fixture/watcher/test.js]: `t.pass();`?

File: test/cli.js [hunk 2]
```diff
@@ -110,3 +114,45 @@ test('pkg-conf: cli takes precedence', function (t) {
...
+		hasChokidar = true;
+	} catch (err) {}
+
+	var child = execCli(['--verbose', '--watch', 'test.js'], 'fixture/watcher', function (err, stdout) {
+		if (err && err.code === 1 && !hasChokidar) {
+			t.comment('chokidar dependency is missing, cannot test watcher');
+			t.match(stdout, 'The optional dependency chokidar failed to install and is required for --watch. Chokidar is likely not supported on your platform.');
+			t.end();
+		} else {
+			t.comment('chokidar dependency is installed, cannot test watcher behavior with missing dependency');
```
Comment (sindresorhus) [inline test/cli.js]: This message is a bit confusing and I don't see the point of it. There's already a warning when `chokidar` is not installed. I don't see the point of commenting that it is installed.

**Comment by sindresorhus** [comment]
// @vdemedes

File: test/cli.js (hunk 2 above)
Comment (novemberborn) [inline test/cli.js]: The test passes either way so you can't obviously tell which branch passed, hence the comment output. Though that still requires you to look at raw TAP so probably not that useful.

Comment (sindresorhus) [inline test/cli.js]: Yes, but I'm only interested if Chokidar is not installed. Otherwise IMHO it's just noise.

**Comment by novemberborn** [comment]
Updated.

**Comment by sindresorhus** [comment]
:+1:
