### PR TITLE
Print the planned and actual assertion count when incorrect.

### LINKED ISSUE #102: When assertion count is incorrect, output the expected and actual values.
I see that the actual count is recorded, but I'm not sure how to see it when running `ava`.

https://github.com/sindresorhus/ava/blob/master/lib/test.js#L150-L158

```
❯ npm test

> npm-check@4.1.2 test /Users/dgreene/projects/npm-check
> xo && ava ./test


  ✖ require Assertion count does not match planned

  1 test failed

  1. require
  Error
    at Test.plan (/Users/dgreene/projects/npm-check/node_modules/ava/lib/test.js:87:19)
    at Test.<anonymous> (/Users/dgreene/projects/npm-check/test/test.js:10:7)
    at step (/Users/dgreene/projects/npm-check/test/test.js:5:273)
    at Test.fn (/Users/dgreene/projects/npm-check/test/test.js:5:99)
```

The above is using using `master` with `power-assert` added.

Similar output using the published version

```
> npm-check@4.1.2 test /Users/dgreene/projects/npm-check
> xo && ava ./test


  ✖ require Assertion count does not match planned

  1 test failed

  1. require
  Error
    at Test.plan (/Users/dgreene/projects/npm-check/node_modules/ava/lib/test.js:59:19)
    at Object.callee$0$0$ (/Users/dgreene/projects/npm-check/test/test.js:10:7)
    at Test.callee$0$0 [as fn] (/Users/dgreene/projects/npm-check/test/test.js:32:26)
```

### PR DESCRIPTION
**Pull request by jamestalmage**
Fixes #102

The assertion error already had `expected` and `actual` properties, but only the tap reporter displays those. Instead of modifying existing reporters to handle the special case of planned assertions, I took the easy way out and just dynamically generated the error message.

### CODE REVIEW

File: lib/test.js [hunk 1]
```diff
@@ -11,6 +11,7 @@ var inspect = require('util').inspect;
 var assert = require('./assert');
 var enhanceAssert = require('./enhance-assert');
 var globals = require('./globals');
+var plur = require('plur');
```
Comment (sindresorhus) [inline lib/test.js]: Should be above relative require calls. Wish we had a ESLint rule for this. (https://github.com/sindresorhus/module-requests/issues/62)

**Comment by novemberborn** [comment]
:shipit:
