### PR TITLE
	watcher: remember failures from previous tests

### LINKED ISSUE #699: Watch mode should remember failures from tests it does not rerun.
## Issue

`failing-test.js`:

```js
import test from 'ava';

test(t => t.fail('oh no!'));
```

`passing-test.j2`:

```js
import test from 'ava';

test(t => t.pass('yeah!'));

// add more tests here
```

Given the above tests in watch mode, if you continue to edit `passing-test.js` (or any file that does not cause `failing-test.js` to be rerun), you will not be reminded that there are previously failing tests which were not rerun.

## Solution

I think we should track previous failures and show a message like:

```
3 passed
2 failing
2 previously failing tests were not rerun
```

The above shows 3 passing and 2 failing tests that were rerun. It also mentions 2 tests that were not rerun because the watch algorithm did not detect any changes.

## Alternate solution

Always rerun files that had failing tests regardless.

### PR DESCRIPTION
**Pull request by novemberborn**
Fixes #699. The watcher tracks how many failures (actual failures, but also rejections and uncaught exceptions) occurred for each test file. After each run, if there are failures from files that were not rerun, the count is added to the logger output.

### CODE REVIEW

File: lib/watcher.js [hunk 1]
```diff
@@ -173,10 +175,68 @@ Watcher.prototype.updateExclusivity = function (file, hasExclusiveTests) {
 	}
 };
 
+Watcher.prototype.trackFailures = function (api) {
```
Comment (jamestalmage) [inline lib/watcher.js]: I don't think this tracking behavior belongs in watcher.

Let's enhance `RunStatus` to track both aggregate and per file failures, and give it the ability to track previous runs.

Here is a possible API:

```js
var testRun = api.run([...listofFiles]);

// someTime later
var previousRun = testRun;
testRun = api.run([...listOfFiles], previousRun);
```

Alternatively, maybe just create an "AggregateStatus" class:

```js
var combinedStatus = new AggregateStatus({
  previousRun: RunStatus-instance,
  currentRun: RunStatus-instance,
  files: list-of-files-that-are-being-rerun, // or not being rerun, whichever makes more sense
  deleted: list-of-deleted-tests
});
```

Comment (novemberborn) [inline lib/watcher.js]: The current approach is relatively clean. We could do something like that if we're going to move more of the watcher functionality into the API maybe, or when we have a clearer idea of what programmatic interface we need to present to editors plugins.

Comment (jamestalmage) [inline lib/watcher.js]: > The current approach is relatively clean

It's clean enough, but `watcher.js` as a whole is getting pretty complex. I'm just looking for ways to separate what it does into logical chunks.

File: api.js [hunk 2]
```diff
@@ -64,7 +64,7 @@ Api.prototype._onTimeout = function (runStatus) {
 
 	runStatus.handleExceptions({
 		exception: new AvaError(message),
-		file: null
+		file: undefined
```
Comment (jamestalmage) [inline api.js]: ?

File: api.js [hunk 3]
```diff
@@ -151,7 +151,7 @@ Api.prototype._run = function (files, _options) {
 					// continue to run.
 					runStatus.handleExceptions({
 						exception: err,
-						file: file
+						file: path.relative('.', file)
```
Comment (jamestalmage) [inline api.js]: This is more consistent with existing behavior in `fork`, etc. But maybe we should be emitting everything as absolute paths and have the reporters handle truncating to relative ones? Seems like it would be best to keep it explicit until we decide to show it to a human.

File: lib/watcher.js (hunk 1 above)
Comment (novemberborn) [inline lib/watcher.js]: Sure. Would be nice to do that later though :)

File: api.js (hunk 2 above)
Comment (novemberborn) [inline api.js]: It was inconsistent.

File: api.js (hunk 3 above)
Comment (novemberborn) [inline api.js]: Sure, but that should be done as a separate task. `fork` emits more of these files so I figured I'd make it consistent with that first.

**Comment by jamestalmage** [comment]
LGTM.

I left a few comments, but they really require further discussion and shouldn't be holding up merging this.

I say :shipit:

File: lib/watcher.js [hunk 4]
```diff
@@ -44,12 +44,10 @@ function Watcher(logger, api, files, sources) {
...
 	this.isTest = makeTestMatcher(files, AvaFiles.defaultExcludePatterns());
 
-	var isFirstRun = true;
 	this.clearLogOnNextRun = true;
+	this.runVector = 0;
 	this.run = function (specificFiles) {
-		if (isFirstRun) {
-			isFirstRun = false;
-		} else {
+		if (this.runVector > 0) {
```
Comment (kevva) [inline lib/watcher.js]: `if (this.runVector)` or `if (this.runVector !== 0)`

File: api.js (hunk 3 above)
Comment (jamestalmage) [inline api.js]: Agreed and understood.

File: lib/watcher.js (hunk 4 above)
Comment (jamestalmage) [inline lib/watcher.js]: Of those two I'd prefer `!== 0`, but I'm not sure why `> 0` is unacceptable. Because it implies `runVector` might be less than zero? Or some other reason?

File: lib/watcher.js (hunk 1 above)
Comment (jamestalmage) [inline lib/watcher.js]: Sure - as stated below - none of my comments need to hold this up.

File: lib/watcher.js (hunk 4 above)
Comment (novemberborn) [inline lib/watcher.js]: I'm trying to avoid implicit conversions. The vector is increasing so `> 0` signifies that more than `!== 0` would, but not fussed either way.

Comment (sindresorhus) [inline lib/watcher.js]: `this.runVector > 0` is the best option here. I would use `!== 0` when it can also be negative.

**Comment by sindresorhus** [comment]
:shipit:
