### PR TITLE
Fix t.throws() behavior to avoid false-positives and regex suport

### LINKED ISSUE #85: assert.throws and promises which resolve to error objects
[Currently](https://github.com/sindresorhus/ava/blob/d14c6e37fa4c9666599e78256cc0c9ccc39d45e5/lib/assert.js#L76-L87), the following test passes:
```js
test('resolve error value', t => {
	t.plan(1);
	t.throws(Promise.resolve(new Error('abc'))); // pass (false negative)
});
```

### LINKED ISSUE #86: assert.throws, promises and regex
[Currently](https://github.com/sindresorhus/ava/blob/d14c6e37fa4c9666599e78256cc0c9ccc39d45e5/lib/assert.js#L76-L87), the last test fails:

```js
test('throw Error and regex', t => {
	t.plan(1);
	t.throws(() => { throw new Error('abc'); }, /b/); // pass (as expected)
});

test('reject error', t => {
	t.plan(1);
	t.throws(Promise.reject(new Error('abc'))); // pass (as expected)
});

test('reject error and regex', t => {
	t.plan(1);
	t.throws(Promise.reject(new Error('abc')), /b/); // fails (false positive)
});
```

### PR DESCRIPTION
**Pull request by vdemedes**
This PR fixes #86 and fixes #85.

It improves `t.throws()`, so that it avoids false-positives results and supports regex, just like native `throws()`.

### CODE REVIEW

**Comment by sindresorhus** [comment]
Super! :)

**Comment by schnittstabil** [comment]
@vdemedes Thanks a lot.

File: lib/assert.js [hunk 1]
```diff
@@ -70,19 +70,21 @@ x.notSame = function (val, expected, msg) {
...
+			.then(function (fnErr) {
+				if (!isFailed) {
+					x.throws(function () {}, err, msg);
 				}
 
 				x.throws(function () {
-					throw value;
+					throw fnErr;
 				}, err, msg);
 			});
```
Comment (schnittstabil) [inline lib/assert.js]: @vdemedes This seems unnecessarily complicated to me. Just a suggestion:
```js
	if (fn && fn.then) {
		return fn
			.then(function () {
				x.throws(function () {}, err, msg);
			}, function (fnErr) {
				x.throws(function () {
					throw fnErr;
				}, err, msg);
			});
	}
```
