### PR TITLE
Display only failed hooks

### LINKED ISSUE #105: after/before/afterEach/beforeEach hooks should not have a title
It doesn't make sense for them to have a title as you're just hooks.

Should we just prevent it being set in the first place?

### PR DESCRIPTION
**Pull request by vdemedes**
This PR fixes #105.

From now on, AVA displays only hooks that failed. This results to a dramatically cleaner output:

**Before**:

screen shot 2015-11-11 at 5 04 02 pm

**After**:

screen shot 2015-11-11 at 5 04 30 pm

### CODE REVIEW

File: lib/runner.js [hunk 1]
```diff
@@ -137,10 +161,11 @@ Runner.prototype._addTestResult = function (test) {
 	this.results.push({
 		duration: test.duration,
 		title: test.title,
-		error: test.assertError
+		error: test.assertError,
+		type: test.type
 	});
 
-	this.emit('test', test.assertError, test.title, test.duration);
+	this.emit('test', test.assertError, test.title, test.duration, test.type);
```
Comment (sindresorhus) [inline lib/runner.js]: Not for this PR, but what do you think about pushing and object here instead of all the arguments? We could just reuse the object in `this.results.push`.

File: test/test.js [hunk 2]
```diff
@@ -918,6 +953,32 @@ test('don\'t display test title, if there is only one anonymous test', function
 	});
 });
 
+test('don\'t display hook title, if it did not fail ', function (t) {
```
Comment (sindresorhus) [inline test/test.js]: no comma needed here and extraneous space at the end.

File: test/test.js [hunk 3]
```diff
@@ -918,6 +953,32 @@ test('don\'t display test title, if there is only one anonymous test', function
...
+		.on('test', function (test) {
+			t.deepEqual(test.err, {});
+			t.is(test.title, 'pass');
+		})
+		.then(function () {
+			t.end();
+		});
+});
+
+test('display hook title, if it failed', function (t) {
```
Comment (sindresorhus) [inline test/test.js]: no comma needed

File: test/test.js [hunk 4]
```diff
@@ -918,6 +953,32 @@ test('don\'t display test title, if there is only one anonymous test', function
...
+	t.plan(2);
+
+	fork(path.join(__dirname, 'fixture', 'hooks-passing.js'))
+		.on('test', function (test) {
+			t.deepEqual(test.err, {});
+			t.is(test.title, 'pass');
+		})
+		.then(function () {
+			t.end();
+		});
```
Comment (sindresorhus) [inline test/test.js]: `.then(t.end);`?

File: test/test.js [hunk 5]
```diff
@@ -918,6 +953,32 @@ test('don\'t display test title, if there is only one anonymous test', function
...
+	t.plan(2);
+
+	fork(path.join(__dirname, 'fixture', 'hooks-failing.js'))
+		.on('test', function (test) {
+			t.is(test.err.name, 'AssertionError');
+			t.is(test.title, 'beforeEach for "pass"');
+		})
+		.then(function () {
+			t.end();
+		});
```
Comment (sindresorhus) [inline test/test.js]: `.then(t.end);`?

File: test/test.js [hunk 6]
```diff
@@ -824,6 +825,40 @@ test('hooks - shared context of any type', function (t) {
...
+	runner.on('test', function (err, title, duration, type) {
+		var test = tests.shift();
+
+		t.is(test.title, title);
+		t.is(test.type, type);
+	});
+
+	runner.run().then(function () {
+		t.end();
+	});
```
Comment (sindresorhus) [inline test/test.js]: `.then(t.end);`?

**Comment by sindresorhus** [comment]
Looks good! Commented some nitpicks inline.

**Comment by sindresorhus** [comment]
// @floatdrop @jamestalmage

File: lib/runner.js [hunk 7]
```diff
@@ -53,14 +53,25 @@ Runner.prototype.addSerialTest = function (title, cb) {
 };
 
 Runner.prototype.addBeforeHook = function (title, cb) {
-	this.tests.before.push(new Test(title, cb));
+	var test = new Test(title, cb);
+	test.type = 'hook';
```
Comment (floatdrop) [inline lib/runner.js]: How about moving types to something like `new Test.hook(title, cb)` (can be done in separate PR)?

Comment (sindresorhus) [inline lib/runner.js]: @floatdrop What would `new Test.hook(title, cb)` be? Just a wrapper function that sets the internal `this.type`?

Comment (floatdrop) [inline lib/runner.js]: @sindresorhus yep. May be this is not worth a shot yet, but in future we could want to eliminate these string constants.

File: lib/runner.js (hunk 1 above)
Comment (vdemedes) [inline lib/runner.js]: Absolutely, was going to do that here at first, but then thought about a new PR :D

File: test/test.js (hunk 4 above)
Comment (vdemedes) [inline test/test.js]: #181 is not merged yet, so it will call `t.end()` with a global context (`t.end()` is not binded yet).

File: lib/runner.js (hunk 7 above)
Comment (vdemedes) [inline lib/runner.js]: imho `new Test.hook(title, cb)` does not look good. In such case, `Test.hook` is a class (function), which has to be uppercase.

File: test/test.js (hunk 4 above)
Comment (sindresorhus) [inline test/test.js]: But this is tape, not AVA.

Comment (vdemedes) [inline test/test.js]: Oh damn it.

File: lib/runner.js (hunk 7 above)
Comment (sindresorhus) [inline lib/runner.js]: Yeah, we can look into this later. It could be a subclass too, `new Hook()`, but I'm not a big fan of that either. Maybe using Symbols as constants. `ava.HOOK_TYPE = Symbol('hook')` or something. But meh.

File: test/test.js (hunk 4 above)
Comment (vdemedes) [inline test/test.js]: Just tried it, does not work, because `fork` resolves with test results: `t.end(results)`.

Comment (sindresorhus) [inline test/test.js]: Oh, nvm then. Sorry about the noise.

Comment (vdemedes) [inline test/test.js]: No probs ;) `runner.then(t.end)` works though!

**Comment by vdemedes** [comment]
@sindresorhus PR updated ;)

**Comment by sindresorhus** [comment]
Ace :)

**Comment by vdemedes** [comment]
giphy
