### PR TITLE
Don't crash watch mode when tests files fail to transpile

### LINKED ISSUE #622: Watch mode crashes when test files fail to transpile
Steps to reproduce:

* Start AVA in watch mode
* Introduce a syntax error, e.g. use `test.('title', t => {})`
* AVA crashes

The error should be logged however AVA should not crash.

### PR DESCRIPTION
**Pull request by novemberborn**
Fixes #622.

Catch exceptions when initially running files. Don't run any tests, just report the exception.

Move test teardown into a callback for the run promise so it can be used when `--match` is used but there are no matches, and when exceptions occur while initially running files.

Teardown causes the test promise to reject, which leads to an attempt to run the tests. Add a guard to prevent this.

### CODE REVIEW

File: api.js [hunk 1]
```diff
@@ -192,11 +192,7 @@ Api.prototype.run = function (files) {
 			self.fileCount = files.length;
 			self.base = path.relative('.', commonPathPrefix(files)) + path.sep;
 
-			var tests = files.map(self._runFile);
-
-			// receive test count from all files and then run the tests
-			var unreportedFiles = self.fileCount;
-
+			var tests = new Array(self.fileCount);
```
Comment (vdemedes) [inline api.js]: Could you explain why is array of N (`self.fileCount`) null elements needed?

**Comment by sindresorhus** [comment]
LGTM

**Comment by sindresorhus** [comment]
@jamestalmage Looks good to you?

File: api.js (hunk 1 above)
Comment (jamestalmage) [inline api.js]: It gets filled with promises for run results [here](https://github.com/sindresorhus/ava/blob/watch-and-syntax-errors/api.js#L248)

**Comment by jamestalmage** [comment]
:+1:

File: api.js (hunk 1 above)
Comment (novemberborn) [inline api.js]: Yea. I'm just preallocating it to the right size.
