### PR TITLE
Fix profiling script and add some tests for it.

### LINKED ISSUE #798: Profile script not working
When running `devtool node_modules/ava/profile.js test.js` it's throwing:

```
Uncaught TypeError: 
/Users/sindresorhus/dev/ava/profile.js
(intermediate value).generateHashForFile is not a function(anonymous function) @ profile.js:71Module._compile @ module.js:425devtoolCompileModule @ /usr/local/lib/node_modules/devtool/lib/require-hook.js:30Module.load @ module.js:356Module._load @ module.js:313Module.require @ module.js:366require @ module.js:385(anonymous function) @ /usr/local/lib/node_modules/devtool/lib/preload.js:76emitOne @ events.js:77emit @ events.js:169
```

// @jamestalmage

### PR DESCRIPTION
**Pull request by jamestalmage**
Fixes #798.

### CODE REVIEW

File: profile.js [hunk 1]
```diff
@@ -95,21 +99,36 @@ events.on('test', function (data) {
...
 
 events.on('results', function (data) {
-	console.profileEnd();
+	if (console.profileEnd) {
+		console.profileEnd();
+	}
 	console.log('RESULTS:', data.stats);
+
+	if (process.exit) {
+		process.exit(data.stats.failCount + uncaughtExceptionCount); // eslint-disable-line
```
Comment (jamestalmage) [inline profile.js]: This could also be fixed by making this file executable and adding a hashbang line.

Does `iron-node`, etc. tolerate hash bangs?

**Comment by novemberborn** [comment]
Sure. AppVeyor is still failing though 😢

**Comment by sindresorhus** [comment]
LGTM
