### PR TITLE
Show error if babel config value is invalid

### LINKED ISSUE #623: Specifying a bad string for the babel config option gives unhelpful error
Using `master` and the following config in `package.json`:

```js
"ava": {
  "babel": "foo"
}
```

Produces the following error:

```
ReferenceError: [BABEL] /dev/project/test.js: Unknown option: base.0. Check out http://babeljs.io/docs/usage/options/ for more info
```

If a uses provides a string shortcut for the "babel" option, we should verify it is one of the allowed ones (currently that list is `default` and `inherit` if I'm not mistaken).

### PR DESCRIPTION
**Pull request by vdemedes**
This PR fixes #623.

If `babel` config value is invalid, AVA now shows an error:

screen shot 2016-03-15 at 8 57 27 pm

### CODE REVIEW

**Comment by vdemedes** [comment]
I'm sure there might be a better error message, so feedback is welcome!

File: cli.js [hunk 1]
```diff
@@ -41,6 +42,18 @@ var conf = pkgConf.sync('ava', {
 	}
 });
 
+// check for valid babel config shortcuts (can be either "default" or "inherit")
+var isValidShortcut = ['default', 'inherit'].indexOf(conf.babel) >= 0;
+
+if (conf.babel.length > 0 && !isValidShortcut) {
```
Comment (novemberborn) [inline cli.js]: Presumably this will crash if `babel` is set to `null`. I'd prefer this to be more explicit:

```js
if (!conf.babel || (typeof conf.babel !== 'object' && conf.babel !== 'default' && conf.babel !== 'inherit')) {
```

Note that `conf.babel` should default to `default` so `!conf.babel` would only occur if it's explicitly set to a falsey value.

File: cli.js [hunk 2]
```diff
@@ -41,6 +42,18 @@ var conf = pkgConf.sync('ava', {
...
+	var message = '';
+	message += 'Value "' + conf.babel + '" in "babel" property of AVA config in package.json is invalid.';
+	message += ' Check out ' + chalk.underline('https://github.com/sindresorhus/ava#es2015-support') + ' for docs on how to configure Babel.';
```
Comment (novemberborn) [inline cli.js]: How about:

> Unexpected Babel configuration for AVA. See https://github.com/sindresorhus/ava#es2015-support for allowed values.

Even if users don't recall where they configured Babel, the GitHub link will make that clear. I do think we should mention the "for AVA" part to make clear we're not talking about `.babelrc` stuff.

Comment (sindresorhus) [inline cli.js]: :+1:

File: cli.js [hunk 3]
```diff
@@ -41,6 +42,18 @@ var conf = pkgConf.sync('ava', {
 	}
 });
 
+// check for valid babel config shortcuts (can be either "default" or "inherit")
+var isValidShortcut = ['default', 'inherit'].indexOf(conf.babel) >= 0;
```
Comment (sindresorhus) [inline cli.js]: `>= 0` → `!== -1`

File: cli.js (hunk 1 above)
Comment (vdemedes) [inline cli.js]: That way it will fail when `babel` config is not even present. It should only check and display this error message, when `babel` config is there and has invalid value.

**Comment by vdemedes** [comment]
PR updated!

File: cli.js (hunk 1 above)
Comment (novemberborn) [inline cli.js]: > That way it will fail when babel config is not even present.

It won't, it has a default value of `"default"`.

Comment (vdemedes) [inline cli.js]: > It won't, it has a default value of "default".

Oh right! Updating PR to handle this case.
